/*
 * This Scala source file was auto generated by running 'gradle buildInit --type scala-library'
 * by 'AMIYA' at '4/15/18 2:25 PM' with Gradle 3.2.1
 *
 * @author AMIYA, @date 4/15/18 2:25 PM
 */
class Library {
  def someLibraryMethod(): Boolean = true
}
